### ISSUE TITLE
Requirements install thrid command issue

### ISSUE THREAD

**Issue by Snickers333** [gacopl/dvmkv2mp4#1]
I believe the third line has one of the quotes (") missing.

echo "deb [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ focal main | sudo tee -a /etc/apt/sources.list

Running these commands results in an output :
![image](https://user-images.githubusercontent.com/73642349/158584663-687ac65c-99f1-4798-8218-5d2f89a33540.png)
And waiting for further input

**Comment by gacopl** [comment]
yup close the quote after main

**Comment by gacopl** [comment]
fixed in readme
