### ISSUE TITLE
PGS2SRT not working on CIFS mounted volumes (dotnet5 cause)

### ISSUE THREAD

**Issue by mtosic** [gacopl/dvmkv2mp4#16]
Hi, thanks for your great work. 
When I tried converting PGS subs on CIFS mounted volume, I get access denied when creating .srt file.

After a bit of googling, it seems its dotnet (5) issue. As PGS2SRT comes both with dotnet 5 and dotnet6 binaries, I've tried starting pgs2srt with dotnet6.

Do you accept PR's? I can make the PGS2SRT part (and readme) with dotnet6 version.

**Comment by gacopl** [comment]
hi yes i do :)

**Comment by mtosic** [comment]
> hi yes i do :)

Made a PR :)
