### ISSUE TITLE
OSX: SRT subtitles don't mux because of chosen filename + Missing requirements

### ISSUE THREAD

**Issue by tommytoch** [gacopl/dvmkv2mp4#19]
Hi,

Using OSX 10.14.6

First of all, many thanks for creating this wonderful piece of software.

After demuxing your program creates files from "movie.mkv" named "movie DV-MP4.eng.srt"
Under OSX Terminal this creates the issue that this subtitle won't be muxed in again in the final stage of the process.
A simple solution would be to remove the space and use a dot. In other words: "movie DV-MP4.eng.srt" should become "movie.DV-MP4.eng.srt"
This behaviour exists (I suppose) because OSX Terminal handles spaces in filenames in a different way compared to linux shell.

A few minor points:

- jq should be added to the OSX requirements (used when converting HDR10+ to DV)
- dotnet5 requirement should be changed to dotnet6

Thanks for looking into this (if possible) and keep up the good work!

**Comment by gacopl** [comment]
hi please run with debug option and paste log output

**Comment by tommytoch** [comment]
Regretfully, I'm an idiot. I misunderstood the -s flag and thought it was enabled by default. I'm truly sorry for wasting your time.

I did however run into in issue when selecting languages. I specified -l eng and yet all subtitles and audio were converted.

I can easily use MP4box -rem to remove the tracks afterwards. So it's not really a problem for me.

However if you wish to check on this, I've attached a mediainfo of the original mkv and the log.

[mediainfo.txt](https://github.com/gacopl/dvmkv2mp4/files/10189425/mediainfo.txt)
[log.txt](https://github.com/gacopl/dvmkv2mp4/files/10189426/log.txt)

**Comment by gacopl** [comment]
in debug mode you should get sub.extracts file please paste. -l works that if it not hits the lang it will keep all of them so maybe instead of eng try English or und,eng

Or its a bug in osx sed so you would probably need to brew install gsed and replace sed with gsed in the script
