### ISSUE TITLE
DV7 converting

### ISSUE THREAD

**Issue by borsodos1947** [gacopl/dvmkv2mp4#2]
Hi!

Last week, the script still worked well for converting DV7 files, but now running the same file gives an error message. Since then, apt-get update; upgrade has updated several components.
![image](https://user-images.githubusercontent.com/101199080/158588615-efb958ad-28e5-46e1-be7c-d40106148b4a.png)

Other users have the same problem
[https://forum.makemkv.com/forum/viewtopic.php?p=120120#p120120](url)

something may have changed

**Comment by gacopl** [comment]
You need to keep mp4box at 1.0.1 this error comes from newest mp4box

śr., 16 mar 2022, 13:25 użytkownik borsodos1947 ***@***.***>
napisał:

**Comment by gacopl** [comment]
Updated readme on how to build 1.0.1
