### ISSUE TITLE
Feature request: mp4 remux

### ISSUE THREAD

**Issue by Skyross** [gacopl/dvmkv2mp4#22]
I have multiple mp4 files with various Dolby Vision profiles unsupported by my TV. Is there any chance to remix them with this tool?

**Comment by gacopl** [comment]
nope but i guess you can demux mp4 and then follow with what's in tool, iirc correctly mp4s with dolbyvision were troublesome to convert, they would loose DolbyVision metadata when demuxing

**Comment by Skyross** [comment]
Thanks for the explanation.
