### ISSUE TITLE
Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by press88** [gacopl/dvmkv2mp4#24]
Whey i try to convert a file (Ubuntu 22.04.1) I receive this log:

Starting Conversions Thu Feb 23 11:05:11 CET 2023
Converting DV8: "The.Last.of.Us.S01E01.Quando.sei.perso.nell.oscurita.WebDL.2160p.DV.Hevc.HDR.E-AC3.ENG.AC3.ITA.ENG.SUBS.mkv"
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
ionice -c 3 ffmpeg -i "The.Last.of.Us.S01E01.Quando.sei.perso.nell.oscurita.WebDL.2160p.DV.Hevc.HDR.E-AC3.ENG.AC3.ITA.ENG.SUBS.mkv" -y -loglevel error -stats -map 0:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc BL_RPU.hevc
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
cp: cannot stat 'The.Last.of.Us.S01E01.Quando.sei.perso.nell.oscurita.WebDL.2160p.DV.Hevc.HDR.E-AC3.ENG.AC3.ITA.ENG.SUBS.*.srt': No such file or directory
cat: audio.exports: No such file or directory
ionice -c 3 MP4Box -add BL_RPU.hevc:dv-profile=8 -add "":sopt:gfreg=ffdmx -lang 2= -name 2="" -delay 2= -brand mp42isom -ab dby1 "The.Last.of.Us.S01E01.Quando.sei.perso.nell.oscurita.WebDL.2160p.DV.Hevc.HDR.E-AC3.ENG.AC3.ITA.ENG.SUBS DV-MP4.mp4"
[Importer] Cannot load filter for input file "BL_RPU.hevc"
Error importing BL_RPU.hevc:dv-profile=8: Requested URL is not valid or cannot be found
cat: audio.exports: No such file or directory
rm: cannot remove '': No such file or directory
rm: cannot remove 'RPU.bin': No such file or directory
rm: cannot remove 'extra.json': No such file or directory
rm: cannot remove 'hdr10plus_metadata.json': No such file or directory
rm: cannot remove 'audio.exports': No such file or directory
rm: cannot remove 'sub.exports': No such file or directory
rm: cannot remove 'BL*hevc': No such file or directory
Conversions runtime: 0:0:0 (hh:mm:ss)

How to resolve?

Thanks

**Comment by press88** [comment]
No, is a Ubuntu PC on AMD Ryzen 3400G

**Comment by gacopl** [comment]
Then you have something miss configed this setup had been tested by many on
Ubuntu 20.04 on x86. Maybe you missed some prerequisites. Go with sucker it
will be easier for you

czw., 23 lut 2023, 11:30 użytkownik press88 ***@***.***>
napisał:

**Comment by gacopl** [comment]
*Docker :)

czw., 23 lut 2023, 11:58 użytkownik Michał Gacek ***@***.***>
napisał:
