### ISSUE TITLE
ppa:savoury1/ffmpeg4  ffmpeg install error

### ISSUE THREAD

**Issue by snpetit** [gacopl/dvmkv2mp4#26]
Hello!
The ffmpeg install from ppa:savoury1/ffmpeg4 repository gives error with docker also:

```
the following packages have unmet dependencies:
 ffmpeg : Depends: libavcodec58 (= 7:4.4.3-0ubuntu1~22.04.sav3)
          Depends: libavfilter7 (= 7:4.4.3-0ubuntu1~22.04.sav3)
          Depends: libavformat58 (= 7:4.4.3-0ubuntu1~22.04.sav3)
 libavdevice58 : Depends: libavcodec58 (= 7:4.4.3-0ubuntu1~22.04.sav3)
                 Depends: libavfilter7 (= 7:4.4.3-0ubuntu1~22.04.sav3)
                 Depends: libavformat58 (= 7:4.4.3-0ubuntu1~22.04.sav3)
E: Unable to correct problems, you have held broken packages.
```

I have read that Savoury made this project donation only, maybe this is the problem?

> [Rob Savoury](https://twitter.com/RobSavoury)
[@RobSavoury](https://twitter.com/RobSavoury)
·
[márc. 25.](https://twitter.com/RobSavoury/status/1639684945764585473)
Do NOT expect any [#SavOS](https://twitter.com/hashtag/SavOS?src=hashtag_click) PPAs requiring FFmpeg to work for you any longer if you have not donated. Non-donaters should disable or remove all [#SavOS](https://twitter.com/hashtag/SavOS?src=hashtag_click) PPAs (ie. ppa:savoury1/*) using FFmpeg, including ppa:savoury1/ffmpeg4, as all further FFmpeg updates are now only for supporters.

**Comment by gacopl** [comment]
closing as build is working again
