### ISSUE TITLE
[Feature suggestion] Allow audio processing and converting to mp4 for regular HDR10 MKVs

### ISSUE THREAD

**Issue by Pocketkid2** [gacopl/dvmkv2mp4#27]
First off, I just want to say that this is an amazing and easy to use program. However, I have a number of HDR10-only MKVs that have DTS tracks (for example, Warner and Fox titles) and I would love to have the automation that this program does when converting those into Dolby MP4 files. How difficult would this feature be to add? If someone can help point me in the right direction I'd be happy to try and submit a PR.

**Comment by gacopl** [comment]
I don't understand what you want. Dts to DD conversion is already there as feature from beginning

converts any truehd, dts etc to high bitrate Dolby Digital Plus, copies without conversion supported tracks like ac3, eac3

If you have new LG that does not have dts i would suggest to use emby Plex for on the fly audio conversion and don't touch original files

**Comment by Pocketkid2** [comment]
@gacopl When I run the command in a directory containing HDR10 only MKVs, it throws an error saying that there are no Dolby Vision/HDR10+ files and exits without doing anything. I don't see any command line options to override that.

**Comment by gacopl** [comment]
Ok will try to address that. Don't know when. But that's because it was not purpose of the tool you could modify the behavior by modifying script ifs. And again instead of converting your library just for this to solve the player issue i would use emby/Plex/jellyfin to convert on fly according to target device needs as this is just audio conversion not very heavy

**Comment by Pocketkid2** [comment]
I don't use a media server, I plug my USB storage directly into my LG TV which has a great built in media player but does not support DTS in any form. So I need to convert my files manually to Dolby. I've done it by hand with ffmpeg but it's a real hassle and I like the automation that this script affords. If you could point me to where in the script the Dolby Vision checking and conversion takes place, I'd be happy to help out. Thanks!

**Comment by gacopl** [comment]
Try your luck here https://github.com/gacopl/dvmkv2mp4/blob/main/dvmkv2mp4#L120 it's cloudy i woudl try disabling that if and see what happens and if it makes it work for you, then just add option switch saying something like -f "force processing even if not DV/HDR10+ file" - but then i would need to change the name of the project lol

**Comment by markg85** [comment]
Ha, funny.
I'm in the **exact** same position as @Pocketkid2 :) (LG tv and media with DTS but a tv that doesn't support it.

There's a couple options.
1. A soft conversion. Aka, this very project but with the addition to convert DTS sounds to Dolby alternatives.
2. A hardware version, a soundbar. See https://www.reddit.com/r/Soundbars/comments/10pjl64/lg_tvs_are_finally_getting_dts_support/

@gacopl It would be super helpful if your project could add a flag like "--convert-dts-to-dolby" or something like. People using this project quite likely (you already have 2 here) want to play their Dolby Vision media on their DV capable TV but face the issue that their TV doesn't support DV from MKV but does from MP4 hence needing to convert it. The sound aspect is simply the next hurdle.

**Comment by gacopl** [comment]
@markg85 this tool sovles exactly that converts DV MKV to DV MP4 (and if there is DTS track it will convert it to DD+ and Also regular DD5.1). 

The thing is you need either DV or HDR10+ MKV to start with which @Pocketkid2 does not have he wishes just convert the sound. But what you need it for Mark it's already there and works

This tool was created because of this need - LG product being inferior i was on the same boat gents :)

**Comment by markg85** [comment]
Ahh, sorry, misunderstood that.
Awesome!! Thank you so much for creating this!

Small disclaimer. I wrote the above while building the docker image and restarting it half a dozen times... Still building... Haven't actually been able to run it yet.

**Comment by gacopl** [comment]
Probably because of that  https://github.com/gacopl/dvmkv2mp4/issues/26
