### ISSUE TITLE
MP4BOX v1.0.1 install issue

### ISSUE THREAD

**Issue by CitizenDev** [gacopl/dvmkv2mp4#32]
Hi.

this seems to not work any more.
```
git clone --depth 1 https://github.com/gpac/gpac.git gpac_public
cd gpac_public
git checkout v1.0.1 
```

`error: pathspec 'v1.0.1' did not match any file(s) known to git`

**Comment by CitizenDev** [comment]
It is related to commit [15004a3](https://github.com/gacopl/dvmkv2mp4/commit/15004a314799673bc5aece737fbb712db64fb1a9) 
git checkout v1.0.1 for gpac will not work with --depth 1

**Comment by gacopl** [comment]
@OnlineArts this is result of #31 please revert thanks

**Comment by OnlineArts** [comment]
That's right, but the whole command is unnecessary: 
```bash
git clone --depth 1 --branch v1.0.1 https://github.com/gpac/gpac.git gpac_public
cd gpac_public
```
works like charm. I'll create a new merge request
