### ISSUE TITLE
Recursion flag feature request

### ISSUE THREAD

**Issue by CitizenDev** [gacopl/dvmkv2mp4#34]
Could a feature be added to also scan through all subfolders in order to convert whole library in one go?

Of course optionally with added flag

**Comment by CitizenDev** [comment]
> 

Can you give me an example how one would do that? Thanks

**Comment by gacopl** [comment]
something along those lines https://unix.stackexchange.com/questions/295965/how-to-use-find-exec-to-execute-command-in-directory-of-found-file-not-curre
