### ISSUE TITLE
Change directory for temp files

### ISSUE THREAD

**Issue by banjopotato** [gacopl/dvmkv2mp4#36]
This is a great tool. Thanks.

My machine has a fairly small root partition and when I run dvmkv2mp4 on large files, I get a warning about not having enough space.

How can I change the script to use another partition (say, /home) for the temporary files? I've looked at the script but don't know what to change.

**Comment by gacopl** [comment]
scripts is using space where it was started so just move the original file to place where you have space and run it there.

**Comment by banjopotato** [comment]
I did that: moved it to ~/bin. Still using root partition…

**Comment by banjopotato** [comment]
I think it must be log files then. I get a ton of these when using it:

`[hevc-h265] SEI user message type 3 size error (3 but 1 remain), skipping SEI message`

**Comment by gacopl** [comment]
log is written where the video files are but maybe mp4box is creating some temp files.
 try adding this switch to mp4box in the script
 
 -tmp (string)
              specify directory for temporary file creation

**Comment by banjopotato** [comment]
That worked! Thanks and thanks for writing this useful script.
