### ISSUE TITLE
Audio sync issuesis introduced in converted file

### ISSUE THREAD

**Issue by Dantrigger** [gacopl/dvmkv2mp4#38]
Hi,  first of all really nice of you to share this great tool.

I'm not sure if this belongs here but I just converted a movie using the tool but for some reason the mp4 has the audio desynced, it starts playing several seconds later. The MKV file doesn't have this issue. Any idea what could be happening?

I'm not sure what to attach so please let me know what should I provide.

Thanks,

**Comment by gacopl** [comment]
it simply means the source video is borked
