### ISSUE TITLE
Installation instructions for Ubuntu leave out important library

### ISSUE THREAD

**Issue by ChrisLynchHPE** [gacopl/dvmkv2mp4#39]
When using WSL Ubuntu 20.04 LTS, the installation instructions omit `zlib1g-dev` package.  The instructions should include:

```bash
sudo apt-get install -y build-essential pkg-config git zlib1g-dev
```

If not, the following error message happens when trying to run `./configure --static-bin` when attempting to compile MP4box from source:

``` text
zlib not found on system or in local libs
```

**Comment by gacopl** [comment]
it's there 
![image](https://github.com/gacopl/dvmkv2mp4/assets/2278688/d79d53b5-cddd-4c76-a706-22024379b1f0)

**Comment by ChrisLynchHPE** [comment]
Hmmm... Thanks. I must have missed that in my copy and paste to execute batches of commands.
