### ISSUE TITLE
Cannot load filter for import file

### ISSUE THREAD

**Issue by ryangodburn** [gacopl/dvmkv2mp4#41]
![image](https://github.com/gacopl/dvmkv2mp4/assets/44278185/29e1ebc2-1f63-4f9f-9dbd-45f1e7cab3da)

**Comment by ryangodburn** [comment]
Hi! I am trying to use this with the docker image and I ended up with this error. I also tried this through ubuntu on windows subsystem for linux and I got the same message.

**Comment by gacopl** [comment]
Looks like the audio extraction failed, make sure the original file has audio

**Comment by gacopl** [comment]
clearly something went wrong with ffmpeg share full log truehd should not be a problem

**Comment by ryangodburn** [comment]
ok i dont know what i did but i tried it again and it worked i think i was either running it without sudo or something messing up with the wsl image storage space.
