### ISSUE TITLE
Cannot create directory "/.gpac" via docker

### ISSUE THREAD

**Issue by Rikiar73574** [gacopl/dvmkv2mp4#42]
im on windows so not optimal setup and i'm running this via docker 
but after the first step i get the following errors:

Cannot create directory "/.gpac": last error 13
Cannot create directory "/.gpac": last error 13
Cannot create directory "/.gpac/Storage": last error 2

**Comment by gacopl** [comment]
looks like permissions error, make sure you mount correct dir into the container and in the place you start the script you have write permissions

**Comment by Rikiar73574** [comment]
just fyi, i was not able to fix this in docker even setting the chmod to 777, but by running the docker run command with sudo and 0:0 as id it seems to have worked with some cleanup mistakes but the mp4 is there at least 
```
0.500 secs Interleaving
rm: cannot remove 'RPU.bin': No such file or directory
rm: cannot remove 'extra.json': No such file or directory
rm: cannot remove 'hdr10plus_metadata.json': No such file or directory
Conversions runtime: 0:3:11 (hh:mm:ss)
```
