### ISSUE TITLE
install & run it without needing Tesseract OCR models

### ISSUE THREAD

**Issue by WilderDrone** [gacopl/dvmkv2mp4#45]
hi

is there a way to run this without installing & running the "Tesseract OCR models" as you have said this will take 6gb and my machine storage space is limited. if this is for extracting subtitles I don't need it because I can download subs directly from emby.

thanks

**Comment by gacopl** [comment]
i think if you edit script and just comment out #processsubs you wont need to install tesseract

**Comment by WilderDrone** [comment]
thanks I will try it that way & report back. cheers
