### ISSUE TITLE
APT Install Error

### ISSUE THREAD

**Issue by albatrosify** [gacopl/dvmkv2mp4#46]
First, let me thank you for this awesome tool, which has helped me many times before!
However on a fresh ubuntu machine, as well as in docker I run into the following error.
Can you check?

```
26.06 Some packages could not be installed. This may mean that you have
26.06 requested an impossible situation or if you are using the unstable
26.06 distribution that some required packages have not yet been created
26.06 or been moved out of Incoming.
26.06 The following information may help to resolve the situation:
26.06
26.06 The following packages have unmet dependencies:
26.10  ffmpeg : Depends: libavdevice58 (= 7:4.4.4-0ubuntu1~20.04.sav1.1) but it is not going to be installed
26.10           Depends: libavfilter7 (= 7:4.4.4-0ubuntu1~20.04.sav1.1)
26.10           Depends: libavformat58 (= 7:4.4.4-0ubuntu1~20.04.sav1.1)
26.11 E: Unable to correct problems, you have held broken packages.
```

**Comment by albatrosify** [comment]
Thanks for that.
I was trying the dev branch docker image now because I ran into an issue with a specific file on main version.

However following the requirements for ubuntu i ran into the same error on main (non docker).

So at some point there is something wrong or incompatible now...

**Comment by gacopl** [comment]
Dev branch is in development it needs specific requirements that are
probably not met yet they are not in readme and not in dockerfile


śr., 17 sty 2024, 20:25 użytkownik LrdHelmchen ***@***.***>
napisał:
