### ISSUE TITLE
eval: line 268: unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by abprohorov** [gacopl/dvmkv2mp4#8]
I have a file where one of audio stream doesn't have language metadata. As the result on line 180
```
as=$(ffprobe -loglevel error -select_streams a -show_entries stream=type:stream=codec_name:stream=index:stream_tags=language:stream_tags=title -of csv=p=0 "$input" | grep $(echo $LANGS | sed 's/,/,\\|,/g') | sed 's/,/\|/g')
```
we have inconsistent list.

Stream #8:
```
# ffprobe -loglevel error -select_streams a -show_entries stream=type:stream=codec_name:stream=index:stream_tags=language:stream_tags=title -of csv=p=0 hp1.mkv
1,ac3,rus,"Dub, Blu-ray"
2,ac3,rus,"MVO, Карусель"
3,ac3,rus,"MVO, Кравец / С.Р.И."
4,ac3,rus,"MVO, Парус Видео / DDV"
5,dts,rus,"DVO, П.Гланц и И.Королева"
6,ac3,rus,"DVO, SDI Media"
7,ac3,rus,"DVO, Киномания / FDV / ""Легендарный"""
8,ac3,"DVO, LDV / ""Легендарный"""
9,ac3,rus,"DVO, С.Визгунов и Н.Гвамичава"
10,ac3,rus,"AVO, С.Визгунов (ранний)"
11,ac3,rus,"AVO, С.Визгунов (поздний)"
12,ac3,rus,"AVO, С.Визгунов (самый поздний)"
13,ac3,rus,"AVO, А.Дольский"
14,ac3,rus,"AVO, Ю.Сербин"
15,dts,rus,"AVO, С.Рябов"
16,ac3,rus,"VO, Л.Векшин"
17,ac3,rus,"VO, Е.Солодухин"
18,ac3,ukr,"MVO, 1+1"
19,ac3,ukr,"MVO, Новый канал"
20,dts,eng,Original
```

I can't found any mention of `default value` for `-show_entries` in ffprobe documentation.

**Comment by gacopl** [comment]
what is your LANGS setting?, by design in such case it should omit the track as it will not match it.
The logic is if LANGS are set it will match only streams that match langs but if it does not match anything it will take all audio streams that are there. In your case you have matches so the. track without lang will get ommited.

You can do 2 things to workaround don't set langs and catch all tracks, or fix the input mkv with mkvtoolnix which should be easy.

I don't see a way to fix it on my side, as i will not guess lang names. And if needed you can catch them all by not setting langs.

I couldhave count the params, or validate the second column with iso lang table and then add default lang when missing but don't have time for this.

I'll keep this open for once i will have time but its low prio for me happy to accept PR though

**Comment by abprohorov** [comment]
Thanks for so quick reply!
I didn't set lang option. Plex shoes this audio track as "unknown".  So, I'll try to make PR for that.

**Comment by gacopl** [comment]
would it be possible for you to share with me short sample of the file ?

**Comment by abprohorov** [comment]
I'm afraid I won't find this file.. But I "fixed" it with mkvtoolnix, just set language manually for the stream. I guess same tool can help with broke any file.
Thou I have an ugly solution but it works:
```
cat <<EOF > test
1,ac3,rus,"Dub, Blu-ray"
2,ac3,rus,"MVO, Карусель"
3,ac3,rus,"MVO, Кравец / С.Р.И."
4,ac3,rus,"MVO, Парус Видео / DDV"
5,dts,rus,"DVO, П.Гланц и И.Королева"
6,ac3,rus,"DVO, SDI Media"
7,ac3,rus,"DVO, Киномания / FDV / ""Легендарный"""
8,ac3,"DVO, LDV / ""Легендарный"""
9,ac3,rus,"DVO, С.Визгунов и Н.Гвамичава"
10,ac3,rus,"AVO, С.Визгунов (ранний)"
11,ac3,rus,"AVO, С.Визгунов (поздний)"
12,ac3,rus,"AVO, С.Визгунов (самый поздний)"
13,ac3,rus,"AVO, А.Дольский"
14,ac3,rus,"AVO, Ю.Сербин"
15,dts,rus,"AVO, С.Рябов"
16,ac3,rus,"VO, Л.Векшин"
17,ac3,rus,"VO, Е.Солодухин"
18,ac3,ukr,"MVO, 1+1"
19,ac3,ukr,"MVO, Новый канал"
20,dts,eng,Original
EOF

cat test | sed -E 's/([0-9]+),([0-9a-z]+),([a-z]+),(.*)/\1|\2|\3|\4/' | sed -E 's/([0-9]+),([0-9a-z]+),(.*)/\1|\2|unknown|\3/'
1|ac3|rus|"Dub, Blu-ray"
2|ac3|rus|"MVO, Карусель"
3|ac3|rus|"MVO, Кравец / С.Р.И."
4|ac3|rus|"MVO, Парус Видео / DDV"
5|dts|rus|"DVO, П.Гланц и И.Королева"
6|ac3|rus|"DVO, SDI Media"
7|ac3|rus|"DVO, Киномания / FDV / ""Легендарный"""
8|ac3|unknown|"DVO, LDV / ""Легендарный"""
9|ac3|rus|"DVO, С.Визгунов и Н.Гвамичава"
10|ac3|rus|"AVO, С.Визгунов (ранний)"
11|ac3|rus|"AVO, С.Визгунов (поздний)"
12|ac3|rus|"AVO, С.Визгунов (самый поздний)"
13|ac3|rus|"AVO, А.Дольский"
14|ac3|rus|"AVO, Ю.Сербин"
15|dts|rus|"AVO, С.Рябов"
16|ac3|rus|"VO, Л.Векшин"
17|ac3|rus|"VO, Е.Солодухин"
18|ac3|ukr|"MVO, 1+1"
19|ac3|ukr|"MVO, Новый канал"
20|dts|eng|Original
```

**Comment by gacopl** [comment]
so the proper code lang for unknown is und - undefined, the thing that broke my stuff was the double quotes so i will try to find sometime to sanitize these values properly

**Comment by Skyross** [comment]
The same exception happened to me. Any advice?

```
dvmkv2mp4 0.3.0-dev - easily convert Dolby Vision or HDR10+ mkvs to Dolby Vision MP4
Created by github.com/gacopl, Released under GPLv3

Starting Conversions Fri Jan  6 01:16:38 UTC 2023
Converting DV7: "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p.mkv"
ionice -c 3 ffmpeg -i "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p.mkv" -y -loglevel error -stats -map 0:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc - -map 0:1 -c:a:0 copy 1.rus.eac3 -map 0:2 -c:a:0 copy 2.rus.eac3 -map 0:3 -c:a:0 copy 3.rus.ac3 -map 0:4 -b:a:0 1024k -c:a:0 eac3 -f eac3 4.eng.eac3 -map 0:5 -c:a:0 copy 5.eng.ac3 -map 0:6 -c:s:0 copy "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.rus6.srt" -map 0:7 -c:s:0 copy "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.rus7.srt" -map 0:8 -c:s:0 copy "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.rus8.srt" -map 0:9 -c:s:0 copy "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.rus9.srt" -map 0:10 -c:s:0 copy "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.eng10.srt" -map 0:11 -c:s:0 copy "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.eng11.srt" -map 0:1 -map 0:2 -map 0:3 -map 0:4 -map 0:5 -map 0:6 -map 0:7 -map 0:8 -map 0:9 -map 0:10 -map 0:11 -c copy -f matroska "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.asm" | ionice -c 3 dovi_tool -m 2 convert --discard -
frame=186696 fps=272 q=-1.0 Lsize=65465488kB time=02:09:46.77 bitrate=68872.3kbits/s speed=11.3x
cp: cannot stat 'The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p.*.srt': No such file or directory
ionice -c 3 MP4Box -add BL_RPU.hevc:dv-profile=8 -add "1.rus.eac3":sopt:gfreg=ffdmx -lang 2=rus -name 2=""Dub" -delay 2=0 -add "2.rus.eac3":sopt:gfreg=ffdmx -lang 3=rus -name 3=""DVO" -delay 3=0 -add "3.rus.ac3":sopt:gfreg=ffdmx -lang 4=rus -name 4=""MVO" -delay 4=0 -add "4.eng.eac3":sopt:gfreg=ffdmx -lang 5=eng -name 5="" -delay 5=0 -add "5.eng.ac3":sopt:gfreg=ffdmx -lang 6=eng -name 6="" -delay 6=0 -chap chapters.list -brand mp42isom -ab dby1 "The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p DV-MP4.mp4"
/usr/local/bin/dvmkv2mp4: eval: line 369: unexpected EOF while looking for matching `"'
/usr/local/bin/dvmkv2mp4: eval: line 370: syntax error: unexpected end of file
Conversions runtime: 0:11:27 (hh:mm:ss)
```

<details>
  <summary>mediainfo output</summary>
  
mediainfo The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p.mkv
General
Unique ID                                : 261404450162988239322199372052870070964 (0xC4A8AA72F33401BF598A7207749E02B4)
Complete name                            : The.Green.Knight.2021.UHD.Blu-Ray.Remux.2160p.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 67.4 GiB
Duration                                 : 2 h 9 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 74.4 Mb/s
Encoded date                             : UTC 2021-10-13 23:37:33
Writing application                      : mkvmerge v62.0.0 ('Apollo') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.4
Attachments                              : poster.jpg

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 9 min
Bit rate                                 : 68.9 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.346
Stream size                              : 62.4 GiB (93%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0010 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 588 cd/m2
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 2 h 9 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 415 MiB (1%)
Title                                    : Dub, Кинопоиск HD
Language                                 : Russian
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 2 h 9 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 415 MiB (1%)
Title                                    : DVO, Кубик в Кубе
Language                                 : Russian
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #3
ID                                       : 4
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 4 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 398 MiB (1%)
Title                                    : MVO, Jaskier
Language                                 : Russian
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Audio #4
ID                                       : 5
ID in the original source medium         : 4352 (0x1100)
Format                                   : MLP FBA 16-ch
Format/Info                              : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name                          : Dolby TrueHD with Dolby Atmos
Codec ID                                 : A_TRUEHD
Duration                                 : 2 h 9 min
Bit rate mode                            : Variable
Bit rate                                 : 3 476 kb/s
Maximum bit rate                         : 5 781 kb/s
Channel(s)                               : 8 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb
Sampling rate                            : 48.0 kHz
Frame rate                               : 1 200.000 FPS (40 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 3.15 GiB (5%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray
Number of dynamic objects                : 11
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

Audio #5
ID                                       : 6
ID in the original source medium         : 4352 (0x1100)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 9 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 594 MiB (1%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #1
ID                                       : 7
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 59 min
Bit rate                                 : 0 b/s
Count of elements                        : 14
Stream size                              : 468 Bytes (0%)
Title                                    : forced
Language                                 : Russian
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 8
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 4 min
Bit rate                                 : 32 b/s
Count of elements                        : 681
Stream size                              : 29.5 KiB (0%)
Title                                    : full
Language                                 : Russian
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 9
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 4 min
Bit rate                                 : 35 b/s
Count of elements                        : 788
Stream size                              : 32.5 KiB (0%)
Title                                    : FOCS
Language                                 : Russian
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 10
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 4 min
Bit rate                                 : 37 b/s
Count of elements                        : 788
Stream size                              : 34.0 KiB (0%)
Title                                    : chrevodoll
Language                                 : Russian
Default                                  : No
Forced                                   : No

Text #5
ID                                       : 11
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 5 min
Bit rate                                 : 21 b/s
Count of elements                        : 829
Stream size                              : 19.9 KiB (0%)
Title                                    : full
Language                                 : English
Default                                  : No
Forced                                   : No

Text #6
ID                                       : 12
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2 h 8 min
Bit rate                                 : 31 b/s
Count of elements                        : 1238
Stream size                              : 29.6 KiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Chapter 01
00:06:55.289                             : en:Chapter 02
00:15:04.445                             : en:Chapter 03
00:25:13.220                             : en:Chapter 04
00:32:26.611                             : en:Chapter 05
00:41:46.545                             : en:Chapter 06
00:48:36.330                             : en:Chapter 07
00:54:25.720                             : en:Chapter 08
01:02:32.623                             : en:Chapter 09
01:09:30.624                             : en:Chapter 10
01:14:43.187                             : en:Chapter 11
01:22:58.974                             : en:Chapter 12
01:30:42.145                             : en:Chapter 13
01:37:10.199                             : en:Chapter 14
01:48:51.691                             : en:Chapter 15
02:00:00.484                             : en:Chapter 16
  
</details>

**Comment by gacopl** [comment]
Yes did your metadata

...name 3=""DVO" -de...


pt., 6 sty 2023, 02:32 użytkownik Skyross ***@***.***>
napisał:

**Comment by Skyross** [comment]
@gacopl Thanks. Now I understand the problem, I've removed any special characters and it is working well now. I've edited metadata with MKVToolNix GUI.
